### ISSUE TITLE
Did my upgrade complete?

### ISSUE THREAD

**Issue by pgattu** [exking/udi-hue-poly#4]
I just updated the Hue node server using the "Update" button in the node server store.  It looks like the update failed reading the log messages below.  But the "Update" button is not available in the node server store anymore.  Did my upgrade complete successfully?  If not, how do I update Hue node server??

```
12/30/2019, 1:57:19 PM - info: Hue(2): n002_88010217b00d0b ST set sucessfully to 0 : UOM 51
12/30/2019, 1:57:19 PM - info: Hue(2): n002_huegrp0 ST set sucessfully to 0 : UOM 51
12/30/2019, 2:03:09 PM - error: NSChild: Install failed - Non-zero exit code: 2
12/30/2019, 2:03:09 PM - error: NSChild: Hue pullRepo: Error: runInstallProcess: undefined
12/30/2019, 2:03:09 PM - error: Error: runInstallProcess: undefined
    at runInstallProcess (/snapshot/polyglot-v2/lib/modules/children.js:45:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
12/30/2019, 2:03:09 PM - error: NSResponse: Success: false - pullRepo: runInstallProcess: undefined
12/30/2019, 2:03:25 PM - info: Roomba(4): Processing command: status
12/30/2019, 2:03:25 PM - info: Roomba(4): n004_rm0062127620 GV4 set sucessfully to 70 : UOM 51
12/30/2019, 2:03:30 PM - info: Roomba(4): Processing command: status
12/30/2019, 2:03:30 PM - info: Roomba(4): n004_rm0062127620 GV4 set sucessfully to 100 : UOM 51
12/30/2019, 2:03:38 PM - info: Hue(2): Processing command: restart
12/30/2019, 2:03:38 PM - info: Hue(2): Processing command: connected
12/30/2019, 2:03:38 PM - info: Hue(2): NodeServer Disconnected.
12/30/2019, 2:03:38 PM - info: MQTTS: Client Disconnected: Hue
12/30/2019, 2:03:38 PM - info: Hue(2): n002_huebridge ST set sucessfully to 0 : UOM 2
12/30/2019, 2:03:39 PM - info: Hue(2): NodeServer Disconnected.
12/30/2019, 2:03:39 PM - info: Hue(2): n002_huebridge ST set sucessfully to 0 : UOM 2
12/30/2019, 2:03:41 PM - info: NS: Starting Local NodeServer Hue profile number 2 :: Version 0.1.10
12/30/2019, 2:03:41 PM - error: NSChild STDERR: Hue:   File "./hue.py", line 219
    LOGGER.debug(f"Hub {hub_idx} {data['type']} {name} {scene_data['type']} {scene_idx}:{scene_id}:{scene_data['name']}")
                                                                                                                       ^
SyntaxError: invalid syntax

12/30/2019, 2:03:41 PM - info: Hue(2): NodeServer Disconnected.
12/30/2019, 2:03:41 PM - info: Hue(2): n002_huebridge ST set sucessfully to 0 : UOM 2

```

**Comment by exking** [comment]
New version requires python 3.6 at least. If you running on Pi - update the OS to Raspbian Buster
