### ISSUE TITLE
Change IP Address and now Hue Poly doesn't recognize Hue Bridge

### ISSUE THREAD

**Issue by RC-Michael** [exking/udi-hue-poly#7]
Polisy Version: 2.2.13
ISY Version: 5.0.16

Issue: Installed a new Router and it assigned new/different ip address to the Hue Bridge. Upon trying to connect the Hue Bridge with the udi-hue-poly resident on Polisy, I found that the old ip address stored in the udi-hue-poly was not reset/changed to the new address and therefore could not find the Hue Bridge.

I’ve tried the following with no success:

Checked for updates on Polisy and restarted
1.)  Added custom parameter with the correct (new) ip address, but Polyglot is still searching for the old ip address
2.)  Attempted multiple times to stop the node server, press the pair button on the Hue Bridge, and then restart the node server 
      but ip address did not change
3.)   Deleted the Hue node server, uninstall it from the Node Store, reinstalled it and then added it. No change in the ip address.

None of these actions worked as you can see from the log below. Is there any way to change the “Using ip from config:” when running udi-hue-poly on Polisy_

2021-05-16 07:09:00,258 Interface polyinterface INFO polyinterface:_startMqtt: Connecting to MQTT... localhost:1883
2021-05-16 07:09:00,262 MainThread polyinterface INFO hue:init: Started Hue Protocol
2021-05-16 07:09:00,326 MQTT polyinterface INFO polyinterface:_connect: MQTT Connected with result code 0 (Success)
2021-05-16 07:09:00,329 MQTT polyinterface INFO polyinterface:_connect: MQTT Subscribing to topic: udi/polyglot/ns/7 - MID: 1 Result: 0
2021-05-16 07:09:00,329 MQTT polyinterface INFO polyinterface:_connect: MQTT Subscribing to topic: udi/polyglot/connections/polyglot - MID: 2 Result: 0
2021-05-16 07:09:00,331 MQTT polyinterface INFO polyinterface:_connect: Sent Connected message to Polyglot
2021-05-16 07:09:00,337 MQTT polyinterface INFO polyinterface:_subscribe: MQTT Subscribed Succesfully for Message ID: 1 - QoS: (0,)
2021-05-16 07:09:00,342 MQTT polyinterface INFO polyinterface:_subscribe: MQTT Subscribed Succesfully for Message ID: 2 - QoS: (0,)
2021-05-16 07:09:00,435 NodeServer polyinterface INFO hue:connect: Saved bridges information is not found
2021-05-16 07:09:00,446 NodeServer polyinterface INFO hue:connect: No bridge configuration found, trying discovery...
2021-05-16 07:09:00,460 NodeServer polyinterface INFO phue:connect: Attempting to connect to the bridge...
2021-05-16 07:09:00,496 NodeServer polyinterface INFO phue:connect: Using ip from config: **Wrong.IP.address**
2021-05-16 07:09:00,503 NodeServer polyinterface INFO phue:connect: Using username from config: PnqvJdfIqwcAeH2Ltu2smFF4rAl9qIhQuB5nU1qE
2021-05-16 07:09:10,525 NodeServer polyinterface ERROR phue:request: GET Request to **Wrong.IP.address**/api/PnqvJdfIqwcAeH2Ltu2smFF4rAl9qIhQuB5nU1qE/lights/ timed out.
Traceback (most recent call last):
File "/var/polyglot/nodeservers/Hue/phue.py", line 651, in request
connection.request(mode, address)
File "/usr/local/lib/python3.7/http/client.py", line 1277, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/usr/local/lib/python3.7/http/client.py", line 1323, in _send_request
self.endheaders(body, encode_chunked=encode_chunked)
File "/usr/local/lib/python3.7/http/client.py", line 1272, in endheaders
self._send_output(message_body, encode_chunked=encode_chunked)
File "/usr/local/lib/python3.7/http/client.py", line 1032, in _send_output
self.send(msg)
File "/usr/local/lib/python3.7/http/client.py", line 972, in send
self.connect()
File "/usr/local/lib/python3.7/http/client.py", line 944, in connect
(self.host,self.port), self.timeout, self.source_address)
File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
raise err
File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
sock.connect(sa)
socket.timeout: timed out
2021-05-16 07:09:10,539 NodeServer polyinterface ERROR hue:_get_lights: Timed out trying to connect to Hue Bridge.
2021-05-16 07:09:10,540 NodeServer polyinterface ERROR hue:connect: Connect: Failed to read Lights from the Hue Bridge

**Comment by houseguy77** [comment]
Has this issue been fixed? I have the same problem.

**Comment by RC-Michael** [comment]
I talked with UD support and they were able to clear the old IP address out of my ISY.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by houseguy77** [comment]
Thanks... I'll talk to them

Rob
